DROP DATABASE IF EXISTS GUESSDB;

CREATE DATABASE GUESSDB;

use GUESSDB;

CREATE TABLE GUESS_COUNT
(
    GCOUNT_ID int NOT NULL AUTO_INCREMENT,
    GCOUNT int NOT NULL,
    PRIMARY KEY (GCOUNT_ID)
);

INSERT INTO GUESS_COUNT (GCOUNT) VALUES(0);